# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink:           pretty

gems: [jekyll-paginate]

# Setup
title:               Md Nafiz Hamid
tagline:             PhD student at Iowa State University
url:                 https://nafiz.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Md Nafiz Hamid
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/nafizh/nafizh.github.io


pages_list:
  About: '/about'
  Research: '/research'
  Archive: '/archive'

# Google services
google_analytics: UA-72747784-1
